import localFont from "next/font/local";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body className={`antialiased`}>
        <div className="wrapper">
          {children}
        </div>
      </body>
    </html>
  );
}
